#!/usr/bin/env bash
# Copyright 2017 Schuberg Philis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eufo pipefail

export SPLUNK_HOST=${SPLUNK_ADDR:-splunk.kube-system}
export SPLUNK_PORT=${SPLUNK_PORT:-8088}
export SPLUNK_PROTOCOL=${SPLUNK_PROTOCOL:-https}
export SPLUNK_TOKEN=${SPLUNK_TOKEN:-00000000-0000-0000-0000-000000000000}
export SPLUNK_INDEX=${SPLUNK_INDEX:-main}
export SPLUNK_SOURCE=${SPLUNK_SOURCE:-fluentd}
export SPLUNK_SOURCETYPE=${SPLUNK_SOURCETYPE:-kubernetes}
export SPLUNK_USEJSON=${SPLUNK_USEJSON:-true}
export SPLUNK_SEND_EVENT_AS_JSON=${SPLUNK_SEND_EVENT_AS_JSON:-true}
export SPLUNK_SEND_BATCHED_EVENTS=${SPLUNK_SEND_BATCHED_EVENTS:-false}

confdir="/etc/td-agent"

cat ${confdir}/td-agent.conf.template | envsubst '$SPLUNK_HOST $SPLUNK_PORT $SPLUNK_PROTOCOL $SPLUNK_TOKEN $SPLUNK_INDEX $SPLUNK_SOURCE $SPLUNK_SOURCETYPE $SPLUNK_USEJSON $SPLUNK_SEND_EVENT_AS_JSON $SPLUNK_SEND_BATCHED_EVENTS' > ${confdir}/td-agent.conf
exec fluentd -c ${confdir}/td-agent.conf "$@"
