---
apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: logging
spec:
  selector:
    app: splunk
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: splunk
  namespace: logging
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: splunk
    spec:
      serviceAccount: fk8splunk
      volumes:
      - name: init-hec-inputs
        emptyDir:
          medium: "Memory"
      initContainers:
      - name: init-hec-token
        image: busybox
        volumeMounts:
        - name: init-hec-inputs
          mountPath: /init
        env:
        - name: SPLUNKHEC_OPTION_token
          valueFrom:
            secretKeyRef:
              name: fk8splunk
              key: SPLUNKHEC_OPTION_token
        command:
          - sh
          - -c
          - echo "Initializing splunk with HEC-token"; echo -e "[http://fk8splunk-token]\ndescription=fk8splunk\ndisabled=0\nindex=main\ntoken=${SPLUNKHEC_OPTION_token}" > /init/inputs.conf
      containers:
      - name: splunk
        image: splunk/universalforwarder
        volumeMounts:
        - name: init-hec-inputs
          mountPath: /opt/splunk/etc/apps/splunk_httpinput/local
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_ENABLE_DEPLOY_SERVER
          value: "false"
        - name: SPLUNK_FORWARD_SERVER_1
          value: "example.com:9997"
        - name: SPLUNK_CMD_1
          value: edit user admin -password fk8splunk-s3cr3t -role admin -auth admin:changeme
        - name: SPLUNK_CMD_2
          value: http-event-collector enable -uri https://localhost:8089 -enable-ssl 1 -auth admin:fk8splunk-s3cr3t
        ports:
        - containerPort: 8088
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 378Mi
        livenessProbe:
          httpGet:
            port: 8088
            path: /services/collector/health
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 8088
            path: /services/collector/health
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
