---
apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: logging
spec:
  selector:
    app: splunk
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: splunk
  namespace: logging
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: splunk
    spec:
      serviceAccount: fk8splunk
      containers:
      - name: splunk
        image: splunk/splunk:7.0.0-monitor
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_ENABLE_DEPLOY_SERVER
          value: "false"
        - name: SPLUNK_FORWARD_SERVER_1
          value: "example.com:9997"
        ports:
        - containerPort: 8088
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 378Mi
        livenessProbe:
          httpGet:
            port: 8088
            path: /services/collector/health
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 8088
            path: /services/collector/health
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
